#!/bin/bash
set -e

USERNAME="developer"
HOME_DIR="/home/${USERNAME}"

# =============================================================================
# 1. SSH key setup
# =============================================================================
SSH_DIR="${HOME_DIR}/.ssh"
mkdir -p "${SSH_DIR}"

# If authorized_keys was mounted or provided via env var, set it up
if [ -n "${SSH_PUBLIC_KEY:-}" ]; then
  echo "${SSH_PUBLIC_KEY}" > "${SSH_DIR}/authorized_keys"
fi

# Generate host keys if not present (persisted via volume)
if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
  ssh-keygen -A
fi

# Fix SSH permissions
chmod 700 "${SSH_DIR}"
[ -f "${SSH_DIR}/authorized_keys" ] && chmod 600 "${SSH_DIR}/authorized_keys"
chown -R ${USERNAME}:${USERNAME} "${SSH_DIR}"

# =============================================================================
# 2. AWS Bedrock configuration
# =============================================================================
AWS_DIR="${HOME_DIR}/.aws"
mkdir -p "${AWS_DIR}"

# Write AWS config if credentials are provided via env vars
if [ -n "${AWS_ACCESS_KEY_ID:-}" ] && [ -n "${AWS_SECRET_ACCESS_KEY:-}" ]; then
  cat > "${AWS_DIR}/credentials" << EOF
[default]
aws_access_key_id = ${AWS_ACCESS_KEY_ID}
aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
$([ -n "${AWS_SESSION_TOKEN:-}" ] && echo "aws_session_token = ${AWS_SESSION_TOKEN}")
EOF

  cat > "${AWS_DIR}/config" << EOF
[default]
region = ${AWS_REGION:-us-east-1}
output = json
EOF

  chown -R ${USERNAME}:${USERNAME} "${AWS_DIR}"
  chmod 600 "${AWS_DIR}/credentials"
  chmod 644 "${AWS_DIR}/config"
fi

# =============================================================================
# 2b. Persist environment vars for SSH sessions
# =============================================================================
# SSH sessions don't inherit container env vars, so write them to a file
# that zshrc can source
ENV_FILE="${HOME_DIR}/.zshrc.local"
cat > "${ENV_FILE}" << EOF
# Auto-generated by entrypoint — env vars from .env / docker-compose
export CLAUDE_CODE_USE_BEDROCK=1
export ANTHROPIC_MODEL="${ANTHROPIC_MODEL:-us.anthropic.claude-sonnet-4-20250514-v1:0}"
export AWS_REGION="${AWS_REGION:-us-east-1}"
export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION:-us-east-1}"
export DOCKER_HOST=unix:///var/run/docker.sock
$([ -n "${AWS_BEARER_TOKEN_BEDROCK:-}" ] && echo "export AWS_BEARER_TOKEN_BEDROCK='${AWS_BEARER_TOKEN_BEDROCK}'")
$([ -n "${AWS_ACCESS_KEY_ID:-}" ] && echo "export AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'")
$([ -n "${AWS_SECRET_ACCESS_KEY:-}" ] && echo "export AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'")
$([ -n "${AWS_SESSION_TOKEN:-}" ] && echo "export AWS_SESSION_TOKEN='${AWS_SESSION_TOKEN}'")
EOF
chown ${USERNAME}:${USERNAME} "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

# =============================================================================
# 2c. Git global config
# =============================================================================
GIT_NAME="${GIT_USER_NAME:-Asik Mydeen}"
GIT_EMAIL="${GIT_USER_EMAIL:-writetoasik@gmail.com}"
su -l ${USERNAME} -c "git config --global user.name '${GIT_NAME}'"
su -l ${USERNAME} -c "git config --global user.email '${GIT_EMAIL}'"
su -l ${USERNAME} -c "git config --global init.defaultBranch main"

# =============================================================================
# 3. Claude Code configuration for Bedrock
# =============================================================================
CLAUDE_CONFIG_DIR="${HOME_DIR}/.claude"
CLAUDE_CODE_CONFIG_DIR="${HOME_DIR}/.config/claude-code"
mkdir -p "${CLAUDE_CONFIG_DIR}" "${CLAUDE_CODE_CONFIG_DIR}"

# Write Claude Code settings if not already present (volume may have persisted ones)
if [ ! -f "${CLAUDE_CODE_CONFIG_DIR}/settings.json" ]; then
  cat > "${CLAUDE_CODE_CONFIG_DIR}/settings.json" << 'EOF'
{
  "permissions": {
    "allow": [
      "Bash(git *)",
      "Bash(npm *)",
      "Bash(npx *)",
      "Bash(node *)",
      "Bash(bun *)",
      "Bash(python3 *)",
      "Bash(pip *)",
      "Bash(aws *)",
      "Bash(ls *)",
      "Bash(cat *)",
      "Bash(mkdir *)",
      "Bash(cp *)",
      "Bash(mv *)",
      "Bash(rm *)",
      "Bash(find *)",
      "Bash(grep *)",
      "Bash(rg *)",
      "Bash(curl *)",
      "Bash(make *)"
    ]
  }
}
EOF
fi

chown -R ${USERNAME}:${USERNAME} "${CLAUDE_CONFIG_DIR}"
chown -R ${USERNAME}:${USERNAME} "${CLAUDE_CODE_CONFIG_DIR}"

# =============================================================================
# 4. Run claude-auto-setup (first-boot or update)
# =============================================================================
SETUP_DIR="${HOME_DIR}/claude-auto-setup"
SETUP_MARKER="${HOME_DIR}/.claude-auto-setup-done"

if [ -d "${SETUP_DIR}" ] && [ ! -f "${SETUP_MARKER}" ]; then
  echo ">>> Running claude-auto-setup install..."
  cd "${SETUP_DIR}"
  # Pull latest if network available
  git pull --ff-only 2>/dev/null || true
  # Run install as the developer user
  su -l ${USERNAME} -c "cd ${SETUP_DIR} && bash install.sh" || {
    echo ">>> claude-auto-setup install had warnings (non-fatal)"
  }
  touch "${SETUP_MARKER}"
  echo ">>> claude-auto-setup complete"
fi

# =============================================================================
# 4b. Install claude-mem plugin (persistent memory across sessions)
# =============================================================================
CLAUDE_MEM_MARKER="${HOME_DIR}/.claude-mem-installed"
if [ ! -f "${CLAUDE_MEM_MARKER}" ]; then
  echo ">>> Installing claude-mem plugin..."
  su -l ${USERNAME} -c 'claude plugin add claude-mem@thedotmack 2>/dev/null' || {
    echo ">>> claude-mem install skipped (non-fatal)"
  }
  touch "${CLAUDE_MEM_MARKER}"
fi

# =============================================================================
# 5. Docker socket access (for Fleet)
# =============================================================================
DOCKER_SOCK="/var/run/docker.sock"
if [ -S "${DOCKER_SOCK}" ]; then
  # Match the socket's GID inside the container so developer user can access it
  SOCK_GID=$(stat -c '%g' "${DOCKER_SOCK}")
  if [ "${SOCK_GID}" != "0" ]; then
    groupmod -g "${SOCK_GID}" docker 2>/dev/null || true
  fi
  # Ensure developer is in the docker group
  usermod -aG docker ${USERNAME} 2>/dev/null || true
  # If socket is owned by root:root, make it group-accessible
  chmod 660 "${DOCKER_SOCK}" 2>/dev/null || true
  chgrp docker "${DOCKER_SOCK}" 2>/dev/null || true
  DOCKER_STATUS="connected (host Podman socket)"
else
  DOCKER_STATUS="not available (no socket mounted)"
fi

# =============================================================================
# 6. Fix ownership on all mounted volumes
# =============================================================================
chown -R ${USERNAME}:${USERNAME} "${HOME_DIR}/projects" 2>/dev/null || true
chown -R ${USERNAME}:${USERNAME} "${HOME_DIR}/.local" 2>/dev/null || true

# =============================================================================
# 7. Print connection info
# =============================================================================
echo "============================================="
echo " Claude Code Dev VM is ready!"
echo "============================================="
echo " SSH:     ssh developer@localhost -p 2222"
echo " User:    ${USERNAME} (sudo enabled)"
echo " Shell:   zsh (oh-my-zsh + robbyrussell)"
echo " Bedrock: CLAUDE_CODE_USE_BEDROCK=1"
echo " Region:  ${AWS_REGION:-us-east-1}"
echo " Docker:  ${DOCKER_STATUS}"
echo " Projects: ~/projects (persistent volume)"
echo "============================================="

# =============================================================================
# 7. Start SSH daemon in foreground
# =============================================================================
exec /usr/sbin/sshd -D -e
